version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-tram-core-micronaut-examples-basic
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-tram-core-micronaut-examples-basic-{{ checksum "gradle.properties" }}
            - eventuate-tram-core-micronaut-examples-basic-
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-tram-core-micronaut-examples-basic-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./build-and-test-all-mysql-binlog-kafka.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
